mx_records: []
  # - { host: "@", priority: 10, value: "mx.zoho.com" }
  # - { host: "@", priority: 20, value: "mx2.zoho.com" }

txt_records: []
  # - { host: "@", value: "v=spf1 include:zoho.com ~all" }

c_records:
  - { host: "www", value: "@" }

a_records:
  - name: "{{ domain_prefix if domain_prefix else '@' }}"
    fqdn: >-
      {%- if domain_prefix|length > 0 -%}
        {{ domain_prefix }}.{{ site_name }}
      {%- else -%}
        {{ site_name }}
      {%- endif -%}
    ip: "{{ ansible_host }}"

ns_records:
  - { host: "@", value: "ns1.digitalocean.com." }
  - { host: "@", value: "ns2.digitalocean.com." }
  - { host: "@", value: "ns3.digitalocean.com." }

