---
- name: Destroy a DigitalOcean Droplet
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    droplet_name: "example-droplet"
  tasks:
    - name: Destroy Droplet
      community.digitalocean.digital_ocean_droplet:
        state: absent
        oauth_token: "{{ do_token }}"
        name: "{{ droplet_name }}"
        unique_name: true
      register: droplet

    - name: Show droplet info
      debug:
        var: droplet 