---
- name: Create a DigitalOcean Droplet
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    droplet_name: "lab-do-web-ubuntu-001"
    region: "ams3"
    size: "s-1vcpu-512mb-10gb"
    image: "ubuntu-24-04-x64"
    droplet_tags: ["lab"]
    ssh_keys: "{{ lookup('env', 'DO_SSH_KEY_FINGERPRINTS').split(',') }}"
    project: "sites"
  tasks:
    - name: Create Droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        oauth_token: "{{ do_token }}"
        name: "{{ droplet_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        image: "{{ image }}"
        tags: "{{ droplet_tags }}"
        ssh_keys: "{{ ssh_keys }}"
        project: "{{ project }}"
      register: droplet

    - name: Show droplet info
      debug:
        var: droplet

    - name: Set public IPv4 fact
      set_fact:
        droplet_public_ip: "{{ (droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public') | list)[0].ip_address }}"

    - name: Show droplet public IP
      debug:
        var: droplet_public_ip

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ droplet_public_ip }}"
        port: 22
        delay: 10
        timeout: 300
        state: started
